file_path = r"c:\Users\villa\sara-frontend\src\app\dashboard\asistencias\page.tsx"

with open(file_path, "r", encoding="utf-8") as f:
    content = f.read()

# 1. Update the records.push to include 'programa'
target_push = """                                    nombre_estudiante: a.nombre_estudiante,
                                    apellido_estudiante: a.apellido_estudiante,
                                    estado: a.estado,
                                    metodo_verificacion: a.metodo_verificacion,"""

replacement_push = """                                    nombre_estudiante: a.nombre_estudiante,
                                    apellido_estudiante: a.apellido_estudiante,
                                    estado: a.estado,
                                    metodo_verificacion: a.metodo_verificacion,
                                    programa: a.programa || prog,"""

if target_push in content:
    print("Found records.push block!")
    content = content.replace(target_push, replacement_push)
else:
    print("FAILED to find records.push block!")

# 2. Update the handleExportarPDF call site at line 1132
target_call = "handleExportarPDF(grupoData, sesionData);"
if target_call in content:
    print("Found call site!")
    content = content.replace(target_call, "handleExportarPDF(grupoData, sesionData, prog, fac);")
else:
    print("FAILED to find call site!")

# 3. Replace the handleExportarPDF function body entirely
lines = content.splitlines(keepends=True)
start_idx = -1
end_idx = -1

for idx, line in enumerate(lines):
    if "const handleExportarPDF =" in line:
        start_idx = idx
        break

for idx, line in enumerate(lines):
    if idx > start_idx and "if (loading)" in line:
        end_idx = idx
        break

print(f"Indices: start={start_idx}, end={end_idx}")

new_func_lines = [
    "    const handleExportarPDF = (grupoData: any, sesionData: any, progName?: string, facName?: string) => {\n",
    "        const sTotal = sesionData.records.length;\n",
    "        const sPresentes = sesionData.records.filter((r: any) => r.estado === 'asistencia' || r.estado === 'asistencia con retraso').length;\n",
    "        const sPct = sTotal > 0 ? Math.round((sPresentes / sTotal) * 100) : 0;\n",
    "        const dateObj = sesionData.fecha ? (() => {\n",
    "            const [y, m, d] = sesionData.fecha.split('-').map(Number);\n",
    "            return new Date(y, m - 1, d);\n",
    "        })() : null;\n",
    "        const dateStr = dateObj ? dateObj.toLocaleDateString('es-ES', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }) : 'Sin Fecha';\n",
    "\n",
    "        const printWindow = window.open('', '_blank');\n",
    "        if (!printWindow) return;\n",
    "\n",
    "        const htmlContent = `\n",
    "            <html>\n",
    "                <head>\n",
    "                    <title>Reporte Oficial de Asistencia - Universidad de Pamplona</title>\n",
    "                    <style>\n",
    "                        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap');\n",
    "                        \n",
    "                        @page {\n",
    "                            size: letter;\n",
    "                            margin: 1.5cm;\n",
    "                        }\n",
    "                        \n",
    "                        body {\n",
    "                            font-family: 'Inter', sans-serif;\n",
    "                            color: #1e293b;\n",
    "                            margin: 0;\n",
    "                            padding: 0;\n",
    "                            background: #ffffff;\n",
    "                            font-size: 11px;\n",
    "                            line-height: 1.5;\n",
    "                        }\n",
    "                        \n",
    "                        .top-strip {\n",
    "                            height: 4px;\n",
    "                            background: linear-gradient(90deg, #003366 0%, #ad3333 100%);\n",
    "                            margin-bottom: 20px;\n",
    "                        }\n",
    "                        \n",
    "                        .header {\n",
    "                            display: flex;\n",
    "                            align-items: center;\n",
    "                            justify-content: space-between;\n",
    "                            border-bottom: 2px solid #003366;\n",
    "                            padding-bottom: 15px;\n",
    "                            margin-bottom: 25px;\n",
    "                        }\n",
    "                        \n",
    "                        .header-logo {\n",
    "                            display: flex;\n",
    "                            align-items: center;\n",
    "                            gap: 12px;\n",
    "                        }\n",
    "                        \n",
    "                        .header-logo svg {\n",
    "                            width: 65px;\n",
    "                            height: 65px;\n",
    "                        }\n",
    "                        \n",
    "                        .header-title-container {\n",
    "                            display: flex;\n",
    "                            flex-direction: column;\n",
    "                        }\n",
    "                        \n",
    "                        .header-title-main {\n",
    "                            font-size: 16px;\n",
    "                            font-weight: 800;\n",
    "                            color: #003366;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.5px;\n",
    "                            margin: 0;\n",
    "                        }\n",
    "                        \n",
    "                        .header-title-sub {\n",
    "                            font-size: 10px;\n",
    "                            font-weight: 600;\n",
    "                            color: #ad3333;\n",
    "                            text-transform: uppercase;\n",
    "                            margin: 2px 0 0 0;\n",
    "                            letter-spacing: 0.5px;\n",
    "                        }\n",
    "                        \n",
    "                        .header-meta {\n",
    "                            text-align: right;\n",
    "                        }\n",
    "                        \n",
    "                        .header-meta-doc {\n",
    "                            font-size: 12px;\n",
    "                            font-weight: 800;\n",
    "                            color: #003366;\n",
    "                            text-transform: uppercase;\n",
    "                            margin: 0;\n",
    "                        }\n",
    "                        \n",
    "                        .header-meta-date {\n",
    "                            font-size: 9px;\n",
    "                            color: #64748b;\n",
    "                            font-weight: 600;\n",
    "                            margin: 3px 0 0 0;\n",
    "                        }\n",
    "                        \n",
    "                        .section-title {\n",
    "                            font-size: 11px;\n",
    "                            font-weight: 800;\n",
    "                            color: #003366;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.75px;\n",
    "                            margin: 25px 0 10px 0;\n",
    "                            border-bottom: 1.5px solid #cbd5e1;\n",
    "                            padding-bottom: 4px;\n",
    "                            page-break-after: avoid;\n",
    "                        }\n",
    "                        \n",
    "                        .horizontal-table {\n",
    "                            width: 100%;\n",
    "                            border-collapse: collapse;\n",
    "                            margin-bottom: 20px;\n",
    "                            background: #ffffff;\n",
    "                        }\n",
    "                        \n",
    "                        .horizontal-table th {\n",
    "                            background: #f8fafc;\n",
    "                            color: #334155;\n",
    "                            font-size: 9px;\n",
    "                            font-weight: 700;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.5px;\n",
    "                            padding: 8px 10px;\n",
    "                            border: 1px solid #cbd5e1;\n",
    "                            text-align: left;\n",
    "                            width: 16.66%;\n",
    "                        }\n",
    "                        \n",
    "                        .horizontal-table td {\n",
    "                            padding: 8px 10px;\n",
    "                            font-size: 10px;\n",
    "                            color: #1e293b;\n",
    "                            border: 1px solid #cbd5e1;\n",
    "                            font-weight: 500;\n",
    "                        }\n",
    "                        \n",
    "                        .stats-grid {\n",
    "                            display: grid;\n",
    "                            grid-template-cols: 1fr 1fr 1fr;\n",
    "                            gap: 15px;\n",
    "                            margin-bottom: 25px;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card {\n",
    "                            border: 1px solid #cbd5e1;\n",
    "                            border-radius: 6px;\n",
    "                            padding: 10px 15px;\n",
    "                            text-align: center;\n",
    "                            background: #f8fafc;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.presentes {\n",
    "                            border-left: 4px solid #166534;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.ausentes {\n",
    "                            border-left: 4px solid #ad3333;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.porcentaje {\n",
    "                            border-left: 4px solid #003366;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-val {\n",
    "                            font-size: 16px;\n",
    "                            font-weight: 800;\n",
    "                            color: #1e293b;\n",
    "                            margin: 0;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.presentes .stat-val {\n",
    "                            color: #166534;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.ausentes .stat-val {\n",
    "                            color: #ad3333;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-card.porcentaje .stat-val {\n",
    "                            color: #003366;\n",
    "                        }\n",
    "                        \n",
    "                        .stat-lbl {\n",
    "                            font-size: 8.5px;\n",
    "                            font-weight: 700;\n",
    "                            color: #64748b;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.5px;\n",
    "                            margin-top: 2px;\n",
    "                        }\n",
    "                        \n",
    "                        .records-table {\n",
    "                            width: 100%;\n",
    "                            border-collapse: collapse;\n",
    "                            margin-bottom: 30px;\n",
    "                        }\n",
    "                        \n",
    "                        .records-table th {\n",
    "                            background: #003366;\n",
    "                            color: #ffffff;\n",
    "                            font-size: 9px;\n",
    "                            font-weight: 700;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.5px;\n",
    "                            padding: 8px 10px;\n",
    "                            border: 1px solid #003366;\n",
    "                            text-align: left;\n",
    "                        }\n",
    "                        \n",
    "                        .records-table td {\n",
    "                            padding: 8px 10px;\n",
    "                            font-size: 10px;\n",
    "                            color: #334155;\n",
    "                            border: 1px solid #e2e8f0;\n",
    "                            border-bottom: 1px solid #cbd5e1;\n",
    "                            font-weight: 500;\n",
    "                        }\n",
    "                        \n",
    "                        .records-table tr:nth-child(even) td {\n",
    "                            background: #f8fafc;\n",
    "                        }\n",
    "                        \n",
    "                        .badge {\n",
    "                            display: inline-block;\n",
    "                            padding: 2px 6px;\n",
    "                            border-radius: 4px;\n",
    "                            font-size: 8px;\n",
    "                            font-weight: 700;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.25px;\n",
    "                        }\n",
    "                        \n",
    "                        .badge-sara {\n",
    "                            background: #eff6ff;\n",
    "                            color: #1e40af;\n",
    "                            border: 0.5px solid #bfdbfe;\n",
    "                        }\n",
    "                        \n",
    "                        .badge-biometria {\n",
    "                            background: #f5f3ff;\n",
    "                            color: #5b21b6;\n",
    "                            border: 0.5px solid #ddd6fe;\n",
    "                        }\n",
    "                        \n",
    "                        .status-badge {\n",
    "                            display: inline-block;\n",
    "                            padding: 2px 6px;\n",
    "                            border-radius: 4px;\n",
    "                            font-size: 8px;\n",
    "                            font-weight: 800;\n",
    "                            text-transform: uppercase;\n",
    "                            letter-spacing: 0.25px;\n",
    "                            text-align: center;\n",
    "                        }\n",
    "                        \n",
    "                        .status-presente {\n",
    "                            background: #f0fdf4;\n",
    "                            color: #166534;\n",
    "                            border: 0.5px solid #bbf7d0;\n",
    "                        }\n",
    "                        \n",
    "                        .status-tarde {\n",
    "                            background: #fffbeb;\n",
    "                            color: #b45309;\n",
    "                            border: 0.5px solid #fef3c7;\n",
    "                        }\n",
    "                        \n",
    "                        .status-ausente {\n",
    "                            background: #fef2f2;\n",
    "                            color: #ad3333;\n",
    "                            border: 0.5px solid #fecaca;\n",
    "                        }\n",
    "                        \n",
    "                        .signatures {\n",
    "                            display: grid;\n",
    "                            grid-template-cols: 1fr 1fr;\n",
    "                            gap: 40px;\n",
    "                            margin-top: 50px;\n",
    "                            page-break-inside: avoid;\n",
    "                        }\n",
    "                        \n",
    "                        .signature-block {\n",
    "                            text-align: center;\n",
    "                        }\n",
    "                        \n",
    "                        .signature-line {\n",
    "                            border-top: 1.5px dashed #64748b;\n",
    "                            margin-bottom: 8px;\n",
    "                            width: 80%;\n",
    "                            margin-left: auto;\n",
    "                            margin-right: auto;\n",
    "                        }\n",
    "                        \n",
    "                        .signature-title {\n",
    "                            font-size: 10px;\n",
    "                            font-weight: 700;\n",
    "                            color: #1e293b;\n",
    "                        }\n",
    "                        \n",
    "                        .signature-subtitle {\n",
    "                            font-size: 8.5px;\n",
    "                            color: #64748b;\n",
    "                            margin-top: 2px;\n",
    "                            font-weight: 600;\n",
    "                        }\n",
    "                        \n",
    "                        @media print {\n",
    "                            body {\n",
    "                                padding: 0;\n",
    "                            }\n",
    "                        }\n",
    "                    </style>\n",
    "                </head>\n",
    "                <body>\n",
    "                    <div class='top-strip'></div>\n",
    "                    \n",
    "                    <div class='header'>\n",
    "                        <div class='header-logo'>\n",
    "                            <svg viewBox='0 0 100 100' xmlns='http://www.w3.org/2000/svg'>\n",
    "                                <circle cx='50' cy='50' r='45' fill='#f8fafc' stroke='#003366' stroke-width='4'/>\n",
    "                                <circle cx='50' cy='50' r='39' fill='none' stroke='#ad3333' stroke-width='1.5' stroke-dasharray='3 2'/>\n",
    "                                <path d='M50 22 L28 42 L35 72 L50 82 L65 72 L72 42 Z' fill='#003366' stroke='#ad3333' stroke-width='2' stroke-linejoin='round'/>\n",
    "                                <path d='M50 28 L35 44 L40 68 L50 76 L60 68 L65 44 Z' fill='#ffffff' stroke='none'/>\n",
    "                                <rect x='42' y='44' width='16' height='12' rx='1' fill='#ad3333'/>\n",
    "                                <path d='M42 50 L58 50 M50 44 L50 56' stroke='#ffffff' stroke-width='1.5'/>\n",
    "                                <polygon points='50,60 54,66 46,66' fill='#003366'/>\n",
    "                            </svg>\n",
    "                            <div class='header-title-container'>\n",
    "                                <h1 class='header-title-main'>Universidad de Pamplona</h1>\n",
    "                                <p class='header-title-sub'>Sistema Integrado de Gestión Académica (SIGA)</p>\n",
    "                            </div>\n",
    "                        </div>\n",
    "                        <div class='header-meta'>\n",
    "                            <h2 class='header-meta-doc'>Reporte Oficial de Asistencia</h2>\n",
    "                            <p class='header-meta-date'>Generado el ${new Date().toLocaleDateString('es-ES', { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' })}</p>\n",
    "                        </div>\n",
    "                    </div>\n",
    "\n",
    "                    <div class='section-title'>Información del Curso</div>\n",
    "                    <table class='horizontal-table'>\n",
    "                        <thead>\n",
    "                            <tr>\n",
    "                                <th>Asignatura</th>\n",
    "                                <th style='text-align: center;'>Grupo</th>\n",
    "                                <th style='text-align: center;'>Aula</th>\n",
    "                                <th>Programa Académico</th>\n",
    "                                <th>Facultad</th>\n",
    "                                <th style='text-align: center;'>Fecha de Sesión</th>\n",
    "                            </tr>\n",
    "                        </thead>\n",
    "                        <tbody>\n",
    "                            <tr>\n",
    "                                <td style='font-weight: 700;'>${grupoData.asignatura || ''} (${grupoData.codAsig || ''})</td>\n",
    "                                <td style='text-align: center; font-weight: 700;'>${grupoData.grupo || ''}</td>\n",
    "                                <td style='text-align: center;'>${sesionData.aula_sesion || grupoData.aula || 'Sin Aula'}</td>\n",
    "                                <td>${progName || ''}</td>\n",
    "                                <td>${facName || ''}</td>\n",
    "                                <td style='text-align: center; font-weight: 700; color: #003366;'>${dateStr}</td>\n",
    "                            </tr>\n",
    "                        </tbody>\n",
    "                    </table>\n",
    "\n",
    "                    <div class='section-title'>Información del Docente</div>\n",
    "                    <table class='horizontal-table'>\n",
    "                        <thead>\n",
    "                            <tr>\n",
    "                                <th>Nombre Completo</th>\n",
    "                                <th style='text-align: center;'>Documento (C.C.)</th>\n",
    "                                <th style='text-align: center;'>Método de Verificación</th>\n",
    "                                <th style='text-align: center;'>Hora Entrada</th>\n",
    "                                <th style='text-align: center;'>Hora Salida</th>\n",
    "                                <th style='text-align: center;'>Estado de Asistencia</th>\n",
    "                            </tr>\n",
    "                        </thead>\n",
    "                        <tbody>\n",
    "                            <tr>\n",
    "                                <td style='font-weight: 700; color: #003366;'>${grupoData.docente || ''}</td>\n",
    "                                <td style='text-align: center;'>${sesionData.docente_num_doc || '—'}</td>\n",
    "                                <td style='text-align: center;'>\n",
    "                                    <span class='badge ${sesionData.docente_metodo_verificacion === 'Biometría' ? 'badge-biometria' : 'badge-sara'}'>\n",
    "                                        ${sesionData.docente_metodo_verificacion || 'N/A'}\n",
    "                                    </span>\n",
    "                                </td>\n",
    "                                <td style='text-align: center;'>\n",
    "                                    ${sesionData.docente_hora_entrada ? new Date(sesionData.docente_hora_entrada).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}\n",
    "                                </td>\n",
    "                                <td style='text-align: center;'>\n",
    "                                    ${sesionData.docente_hora_salida ? new Date(sesionData.docente_hora_salida).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}\n",
    "                                </td>\n",
    "                                <td style='text-align: center;'>\n",
    "                                    <span class='status-badge ${\n",
    "                                        sesionData.docente_estado_asistencia === 'asistencia' ? 'status-presente' :\n",
    "                                        sesionData.docente_estado_asistencia === 'asistencia con retraso' ? 'status-tarde' : 'status-ausente'\n",
    "                                    }'>\n",
    "                                        ${sesionData.docente_estado_asistencia === 'asistencia' ? 'Presente' :\n",
    "                                          sesionData.docente_estado_asistencia === 'asistencia con retraso' ? 'Tarde' : 'Ausente'}\n",
    "                                    </span>\n",
    "                                </td>\n",
    "                            </tr>\n",
    "                        </tbody>\n",
    "                    </table>\n",
    "\n",
    "                    <div class='stats-grid'>\n",
    "                        <div class='stat-card presentes'>\n",
    "                            <p class='stat-val'>${sPresentes}</p>\n",
    "                            <p class='stat-lbl'>Estudiantes Presentes</p>\n",
    "                        </div>\n",
    "                        <div class='stat-card ausentes'>\n",
    "                            <p class='stat-val'>${sTotal - sPresentes}</p>\n",
    "                            <p class='stat-lbl'>Estudiantes Ausentes</p>\n",
    "                        </div>\n",
    "                        <div class='stat-card porcentaje'>\n",
    "                            <p class='stat-val'>${sPct}%</p>\n",
    "                            <p class='stat-lbl'>Porcentaje de Asistencia</p>\n",
    "                        </div>\n",
    "                    </div>\n",
    "\n",
    "                    <div class='section-title'>Registro de Asistencia de Estudiantes</div>\n",
    "                    <table class='records-table'>\n",
    "                        <thead>\n",
    "                            <tr>\n",
    "                                <th style='width: 25%;'>Nombre Completo</th>\n",
    "                                <th style='width: 15%; text-align: center;'>Documento</th>\n",
    "                                <th style='width: 22%;'>Programa Académico</th>\n",
    "                                <th style='width: 12%; text-align: center;'>Método</th>\n",
    "                                <th style='width: 9%; text-align: center;'>Entrada</th>\n",
    "                                <th style='width: 9%; text-align: center;'>Salida</th>\n",
    "                                <th style='width: 8%; text-align: center;'>Estado</th>\n",
    "                            </tr>\n",
    "                        </thead>\n",
    "                        <tbody>\n",
    "                            ${sesionData.records.map((a: any) => `\n",
    "                                <tr>\n",
    "                                    <td style='font-weight: 700; color: #1e293b;'>${a.nombre_estudiante || ''} ${a.apellido_estudiante || ''}</td>\n",
    "                                    <td style='text-align: center; font-family: monospace;'>${a.num_doc || '—'}</td>\n",
    "                                    <td>${a.programa || progName || ''}</td>\n",
    "                                    <td style='text-align: center;'>\n",
    "                                        <span class='badge ${a.metodo_verificacion === 'Biometría' ? 'badge-biometria' : 'badge-sara'}'>\n",
    "                                            ${a.metodo_verificacion || 'N/A'}\n",
    "                                        </span>\n",
    "                                    </td>\n",
    "                                    <td style='text-align: center;'>\n",
    "                                        ${a.hora_entrada ? new Date(a.hora_entrada).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}\n",
    "                                    </td>\n",
    "                                    <td style='text-align: center;'>\n",
    "                                        ${a.hora_salida ? new Date(a.hora_salida).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}\n",
    "                                    </td>\n",
    "                                    <td style='text-align: center;'>\n",
    "                                        <span class='status-badge ${\n",
    "                                            a.estado === 'asistencia' ? 'status-presente' : a.estado === 'asistencia con retraso' ? 'status-tarde' : 'status-ausente'\n",
    "                                        }'>\n",
    "                                            ${a.estado === 'asistencia' ? 'Presente' : a.estado === 'asistencia con retraso' ? 'Tarde' : 'Ausente'}\n",
    "                                        </span>\n",
    "                                    </td>\n",
    "                                </tr>\n",
    "                            `).join('')}\n",
    "                        </tbody>\n",
    "                    </table>\n",
    "\n",
    "                    <div class='signatures'>\n",
    "                        <div class='signature-block'>\n",
    "                            <div class='signature-line'></div>\n",
    "                            <div class='signature-title'>${grupoData.docente}</div>\n",
    "                            <div class='signature-subtitle'>Docente de la Materia</div>\n",
    "                            <div class='signature-subtitle'>C.C. ${sesionData.docente_num_doc || '__________________'}</div>\n",
    "                        </div>\n",
    "                        <div class='signature-block'>\n",
    "                            <div class='signature-line'></div>\n",
    "                            <div class='signature-title'>Firma Institucional</div>\n",
    "                            <div class='signature-subtitle'>Universidad de Pamplona</div>\n",
    "                            <div class='signature-subtitle'>Representante SIGA / Control Académico</div>\n",
    "                        </div>\n",
    "                    </div>\n",
    "\n",
    "                    <script>\n",
    "                        window.onload = function() {\n",
    "                            window.print();\n",
    "                            setTimeout(function() { window.close(); }, 500);\n",
    "                        };\n",
    "                    </script>\n",
    "                </body>\n",
    "            </html>\n",
    "        `;\n",
    "\n",
    "        printWindow.document.open();\n",
    "        printWindow.document.write(htmlContent);\n",
    "        printWindow.document.close();\n",
    "    };\n"
]

new_lines = lines[:start_idx] + new_func_lines + lines[end_idx:]

with open(file_path, "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print("SUCCESS: Overwrote handleExportarPDF flawlessly!")
